Write-Host " Main Menu :" -ForegroundColor yellow;
Write-Host "";
Write-Host '    1. '$Menu1  -ForegroundColor blue;
Write-Host '    2. '$Menu2  -ForegroundColor red;
Write-Host '    3. '$Menu3 -ForegroundColor gray;
Write-Host '    4. '$Menu4 -ForegroundColor magenta;
Write-Host '    5. '$Menu5 -ForegroundColor yellow;
Write-Host '   ';
Write-Host '    q.  Quit' -ForegroundColor DarkGreen;
Write-Host '    99.'$Menu99 -ForegroundColor DarkGray;
Write-Host ""  -ForegroundColor Magenta;
