cls
Write-Host '      ____              __        '
Write-Host '     / __ \   ____ _   / /      ___ '
Write-Host '    / / / /  / __ `/  / /      / _ \'
Write-Host '   / /_/ /  / /_/ /  / /___   /  __/'
Write-Host '  /_____/   \__,_/  /_____/   \___/ '
Write-Host ''
Write-Host '    +-+-+-+-+-+-+-+-+-+-+ +-+-+-+'
Write-Host '    |P|o|w|e|r|s|h|e|l|l| |C|L|I|'
Write-Host '    +-+-+-+-+-+-+-+-+-+-+ +-+-+-+'
Write-Host ''
Write-Host '  >> Author : David Lejeune'
Write-Host '  >> Created : 27/09/2016'
Write-Host ''
