#feeding the narcistic beast
"# Description"
"# -----------"
"# Windows Management tool "
"# via homebrew powershell enviroment"
"#"
"# Author : David Lejeune"
"# Created : 03/11/2016"
"#"
"# Task goals"
"# ----------"
"# Managing varying tasks on Windows OS via CLI"
"# 1)Files handling"
"#      - cleaning up files to File Hub"
"#      - Logging and/or deleting big files"
"# 2)Backup"
"# 2)Handle GIT repositories"
""
